
export const INTselectors = {

  PresentationDemo : '.DemoRow__homeListRow__3zmQ8',
  PresentBtn :'.ui.blue.large.circular.button',
  PresentDemoBtn : '[class="ui green circular button"]',
  PreviewDemo : '[class="ui green basic circular button"]',
  Toolbar :'[id="Presentation__showToolbarBtnContainer__2nFBw"]',
  Next : '.right.chevron.icon',
  Previous : '.left.chevron.icon',
  Question : '.question.circle.outline.icon',
  AddQuestion : '#PresentationQuestionsForm__newQuestionContainer__3-IqV textarea',
  Save : '.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .ui.buttons .ui.button',
  SaveClose : '.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .ui.buttons .ui.primary.button',
  DeleteQuestion :'.PresentationQuestionsForm__questionAction__2jhkd .ui.mini.basic.circular.icon.button',
  EditQuestion : '.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .PresentationQuestionsForm__questionRow__2GKNI',
  EditQ :'.InlineEditableText__editingContainer__2b4HE textarea',
  GreenSave : '.ui.green.mini.basic.circular.button', 
  NStep : '.list.ol.icon',
  ExitX : '.close.icon',
  MarkasAnswered :'.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .ui.button',
  AddNextStep: '#PresentationNextStepsForm__newNextStepContainer__3JVWO textarea',
  Assignee :'.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .EditableNextStepRow__nextStepRowCompact__1qQSj',
  DueDate : '.EditableNextStepRow__nextStepDueDate__f3Dag',
  Date : '.react-datepicker__day.react-datepicker__day--020',
  EditNextStep : '.ui.top.center.popup.transition.visible.Presentation__menuItemPopup__C5bUJ .EditableNextStepRow__nextStepTitleContainer__1zpYN',
  EditNS : '.InlineEditableText__editingContainer__2b4HE textarea',
  DeleteNS : '.EditableNextStepRow__nextStepAction__3MpwC .ui.mini.basic.circular.icon.button',
  Delete :'.ui.red.mini.button.deleteButton',
  JumpTo : '.mail.forward.icon',
  Anotherslide: '.PresentationTimeline__timelineItem__2fv-V .SlideThumbnail__slideThumbContainer__2odCR.SlideThumbnail__inTimeline__YKOZ0',
  URLs : '#browser-modal-url-input',
  REFRESH : '.refresh.icon',
  ZoomOut : '.zoom-out.icon',
  ZoomIn : '.zoom-in.icon',
  Passwords : '.key.icon',
  DevTools : '.code.icon',
  GoBack :'.arrow.left.icon',
  GoForward :'.arrow.right.icon',
  ResizeWindow : '.mobile.alternate.icon',
  ClearStorage :'.eraser.icon',

}

